# -*- coding: utf-8 -*-

TEXTOS = {

    # ==============================================================
    'es': {
        'titulo':        'SISTEMA CRT DE SUPERVIVENCIA',
        'inicio':        'IDENTIFICACION DEL SUJETO',
        'nombre':        'NOMBRE',
        'origen':        'PROFESION / ORIGEN',
        'boton_inicio':  'INICIAR PROTOCOLO',
        'hp':            'VITALIDAD',
        'lvl':           'NIVEL',
        'exp':           'EXPERIENCIA',
        'hambre':        'NUTRICION',
        'dinero':        'CREDITOS',
        'dias':          'DIAS SOBREVIVIDOS',
        'posicion':      'SECTOR ACTUAL',
        'sp':            'PUNTOS DE MEJORA',
        'mochila':       'INVENTARIO',
        'peligro':       'NIVEL DE PELIGRO',
        'curar':         'USAR',
        'atacar':        'ATACAR',
        'registrar':     'REGISTRAR ZONA',
        'equipar':       'EQUIPAR',
        'desequipar':    'DESEQUIPAR',
        'ranking':       'RANKING GLOBAL',
        'habilidades':   'HABILIDADES',
        'aprender':      'ADQUIRIR',
        'comprar':       'COMPRAR',
        'ignorar':       'IGNORAR',
        'estado_medico': 'ESTADO MEDICO',
        'estable':       'BIO-DATA ESTABLE',
        'biometria':     'BIO-DATA',
        'mapa_politico': 'MAPA POLITICO',
        'cerrar':        'CERRAR',
        'huir':          'HUIR',
        'vats_titulo':   'V.A.T.S. — APUNTAR',
        'parte_cabeza':     'CABEZA',
        'parte_torso':      'TORSO',
        'parte_brazo_izq':  'BRAZO IZQ',
        'parte_brazo_der':  'BRAZO DER',
        'parte_pierna_izq': 'PIERNA IZQ',
        'parte_pierna_der': 'PIERNA DER',
        'slot_cabeza':   'CABEZA',
        'slot_torso':    'TORSO',
        'slot_mano_der': 'ARMA',
        'slot_espalda':  'MOCHILA',
        'slot_pies':     'PIES',
        'crafteo':       'CRAFTEO',
        'craftear':      'CRAFTEAR',
        'materiales':    'MATERIALES',
        'zona_segura':       'ZONA SEGURA',
        'zona_peligrosa':    'ZONA PELIGROSA',
        'edificios':         'EDIFICIOS',
        'muerte_anterior':   'MUERTE ANTERIOR',
        'herida_abierta': 'HEMORRAGIA',
        'irradiado':      'RADIACION',
        'infectado':      'INFECTADO',
        'cat_combate':       'COMBATE',
        'cat_supervivencia': 'SUPERVIVENCIA',
        'cat_recursos':      'RECURSOS',
        'cat_exploracion':   'EXPLORACION',
        # EVENTOS
        'ev_superviviente':  'SUPERVIVIENTE ENCONTRADO',
        'ev_trampa':         'TRAMPA DETECTADA',
        'ev_cadaver':        'CADAVER EN EL CAMINO',
        'ev_radio':          'SENAL DE RADIO',
        'ev_lluvia':         'LLUVIA ACIDA',
        'ev_explosion':      'EXPLOSION LEJANA',
        'ev_manada':         'MANADA DE ZOMBIS',
        'rescatar':          'RESCATAR',
        'huir_evento':       'HUIR',
        'registrar_cadaver': 'REGISTRAR',
        'ignorar_trampa':    'RODEAR',
        'idioma':            'IDIOMA',
        'clases': {
            'Policia': 'Policia', 'Medico': 'Medico', 'Militar': 'Militar',
            'Vagabundo': 'Vagabundo', 'Lenador': 'Lenador', 'Civil': 'Civil',
            'Artista Marcial': 'Artista Marcial', 'Catedratico': 'Catedratico',
            'Agricultor': 'Agricultor',
            'Policía': 'Policia', 'Médico': 'Medico', 'Leñador': 'Lenador',
            'Catedrático': 'Catedratico',
        },
        'objetos': {
            # armas
            'Pistola 9mm': 'Pistola 9mm', 'Rifle': 'Rifle de Caza',
            'Escopeta': 'Escopeta', 'Hacha': 'Hacha de Mano',
            'Cuchillo': 'Cuchillo', 'Katana': 'Katana Oxidada',
            'Machete': 'Machete', 'Bate de beisbol': 'Bate de Beisbol',
            'Lanza artesanal': 'Lanza Artesanal',
            # equipo
            'Exoesqueleto': 'Exoesqueleto', 'Chaleco': 'Chaleco Antibalas',
            'Armadura Placas': 'Armadura de Placas', 'Casco Militar': 'Casco Militar',
            'Gafas Tacticas': 'Gafas Tacticas', 'Botas Tacticas': 'Botas Tacticas',
            'Rodilleras': 'Rodilleras', 'Mochila Grande': 'Mochila Grande',
            'Mochila Tactica': 'Mochila Tactica',
            # curativos / consumibles
            'Botiquin': 'Botiquin', 'Botiquín': 'Botiquin',
            'Venda': 'Venda', 'Vendas': 'Vendas',
            'Lata de comida': 'Lata de Comida',
            'Racion Energetica': 'Racion Energetica',
            'Agua Purificada': 'Agua Purificada',
            'Antibioticos': 'Antibioticos', 'Morfina': 'Morfina',
            'Azada': 'Azada', 'Mapa': 'Mapa',
            # materiales crafteo
            'Trapo': 'Trapo', 'Gasolina': 'Gasolina',
            'Botella vacia': 'Botella Vacia', 'Alcohol': 'Alcohol',
            'Palo': 'Palo', 'Cuerda': 'Cuerda',
            'Chatarra metalica': 'Chatarra Metalica',
            'Cable': 'Cable', 'Lata vacia': 'Lata Vacia',
            'Azucar': 'Azucar', 'Agua sucia': 'Agua Sucia',
            'Pastilla potabilizadora': 'Pastilla Potabilizadora',
            # crafteados
            'Coctel Molotov': 'Coctel Molotov',
            'Trampa Explosiva': 'Trampa Explosiva',
            'Botiquin Mejorado': 'Botiquin Mejorado',
            'Rifle Modificado': 'Rifle Modificado',
        },
    },

    # ==============================================================
    'en': {
        'titulo':        'SURVIVAL CRT SYSTEM',
        'inicio':        'SUBJECT IDENTIFICATION',
        'nombre':        'NAME',
        'origen':        'PROFESSION / ORIGIN',
        'boton_inicio':  'START PROTOCOL',
        'hp':            'VITALITY',
        'lvl':           'LEVEL',
        'exp':           'EXPERIENCE',
        'hambre':        'NUTRITION',
        'dinero':        'CREDITS',
        'dias':          'DAYS SURVIVED',
        'posicion':      'CURRENT SECTOR',
        'sp':            'SKILL POINTS',
        'mochila':       'INVENTORY',
        'peligro':       'DANGER LEVEL',
        'curar':         'USE',
        'atacar':        'ATTACK',
        'registrar':     'SCAVENGE',
        'equipar':       'EQUIP',
        'desequipar':    'UNEQUIP',
        'ranking':       'GLOBAL RANKING',
        'habilidades':   'SKILLS',
        'aprender':      'LEARN',
        'comprar':       'BUY',
        'ignorar':       'IGNORE',
        'estado_medico': 'MEDICAL STATUS',
        'estable':       'BIO-DATA STABLE',
        'biometria':     'BIO-DATA',
        'mapa_politico': 'POLITICAL MAP',
        'cerrar':        'CLOSE',
        'huir':          'FLEE',
        'vats_titulo':   'V.A.T.S. — AIM',
        'parte_cabeza':     'HEAD',
        'parte_torso':      'TORSO',
        'parte_brazo_izq':  'LEFT ARM',
        'parte_brazo_der':  'RIGHT ARM',
        'parte_pierna_izq': 'LEFT LEG',
        'parte_pierna_der': 'RIGHT LEG',
        'slot_cabeza':   'HEAD',
        'slot_torso':    'TORSO',
        'slot_mano_der': 'WEAPON',
        'slot_espalda':  'BACKPACK',
        'slot_pies':     'FEET',
        'crafteo':       'CRAFTING',
        'craftear':      'CRAFT',
        'materiales':    'MATERIALS',
        'zona_segura':       'SAFE ZONE',
        'zona_peligrosa':    'DANGER ZONE',
        'edificios':         'BUILDINGS',
        'muerte_anterior':   'PREV. DEATH',
        'herida_abierta': 'BLEEDING',
        'irradiado':      'IRRADIATED',
        'infectado':      'INFECTED',
        'cat_combate':       'COMBAT',
        'cat_supervivencia': 'SURVIVAL',
        'cat_recursos':      'RESOURCES',
        'cat_exploracion':   'EXPLORATION',
        'ev_superviviente':  'SURVIVOR FOUND',
        'ev_trampa':         'TRAP DETECTED',
        'ev_cadaver':        'CORPSE ON THE ROAD',
        'ev_radio':          'RADIO SIGNAL',
        'ev_lluvia':         'ACID RAIN',
        'ev_explosion':      'DISTANT EXPLOSION',
        'ev_manada':         'ZOMBIE HORDE',
        'rescatar':          'RESCUE',
        'huir_evento':       'FLEE',
        'registrar_cadaver': 'LOOT BODY',
        'ignorar_trampa':    'GO AROUND',
        'idioma':            'LANGUAGE',
        'clases': {
            'Policia': 'Police Officer', 'Medico': 'Doctor', 'Militar': 'Soldier',
            'Vagabundo': 'Drifter', 'Lenador': 'Lumberjack', 'Civil': 'Civilian',
            'Artista Marcial': 'Martial Artist', 'Catedratico': 'Professor',
            'Agricultor': 'Farmer',
            'Policía': 'Police Officer', 'Médico': 'Doctor',
            'Leñador': 'Lumberjack', 'Catedrático': 'Professor',
        },
        'objetos': {
            'Pistola 9mm': '9mm Pistol', 'Rifle': 'Hunting Rifle',
            'Escopeta': 'Shotgun', 'Hacha': 'Hand Axe',
            'Cuchillo': 'Knife', 'Katana': 'Rusty Katana',
            'Machete': 'Machete', 'Bate de beisbol': 'Baseball Bat',
            'Lanza artesanal': 'Improvised Spear',
            'Exoesqueleto': 'Exoskeleton', 'Chaleco': 'Bulletproof Vest',
            'Armadura Placas': 'Plate Armor', 'Casco Militar': 'Military Helmet',
            'Gafas Tacticas': 'Tactical Goggles', 'Botas Tacticas': 'Tactical Boots',
            'Rodilleras': 'Knee Pads', 'Mochila Grande': 'Large Backpack',
            'Mochila Tactica': 'Tactical Backpack',
            'Botiquin': 'Med Kit', 'Botiquín': 'Med Kit',
            'Venda': 'Bandage', 'Vendas': 'Bandages',
            'Lata de comida': 'Canned Food',
            'Racion Energetica': 'Energy Ration',
            'Agua Purificada': 'Purified Water',
            'Antibioticos': 'Antibiotics', 'Morfina': 'Morphine',
            'Azada': 'Hoe', 'Mapa': 'Map',
            'Trapo': 'Rag', 'Gasolina': 'Gasoline',
            'Botella vacia': 'Empty Bottle', 'Alcohol': 'Alcohol',
            'Palo': 'Stick', 'Cuerda': 'Rope',
            'Chatarra metalica': 'Metal Scrap',
            'Cable': 'Wire', 'Lata vacia': 'Empty Can',
            'Azucar': 'Sugar', 'Agua sucia': 'Dirty Water',
            'Pastilla potabilizadora': 'Purif. Tablet',
            'Coctel Molotov': 'Molotov Cocktail',
            'Trampa Explosiva': 'Explosive Trap',
            'Botiquin Mejorado': 'Enhanced Med Kit',
            'Rifle Modificado': 'Modified Rifle',
        },
    },

    # ==============================================================
    'eu': {
        'titulo':        'IRAUPENERAKO CRT SISTEMA',
        'inicio':        'SUBJEKTUAREN IDENTIFIKAZIOA',
        'nombre':        'IZENA',
        'origen':        'LANBIDEA / JATORRIA',
        'boton_inicio':  'PROTOKOLOA HASI',
        'hp':            'BIZITZA-ENERGIA',
        'lvl':           'MAILA',
        'exp':           'ESPERIENTZIA',
        'hambre':        'NUTRIZIOA',
        'dinero':        'KREDITUAK',
        'dias':          'BIZIRAUTEKO EGUNAK',
        'posicion':      'UNEKO SEKTOREA',
        'sp':            'TREBETASUN PUNTUAK',
        'mochila':       'INBENTARIOA',
        'peligro':       'ARRISKU MAILA',
        'curar':         'ERABILI',
        'atacar':        'ERASO',
        'registrar':     'ARAKATU',
        'equipar':       'EKIPATU',
        'desequipar':    'DESEKIPATU',
        'ranking':       'RANKING GLOBALA',
        'habilidades':   'TREBETASUNAK',
        'aprender':      'IKASI',
        'comprar':       'EROSI',
        'ignorar':       'EZIKUSI',
        'estado_medico': 'EGOERA MEDIKOA',
        'estable':       'BIO-DATUAK EGONKORRAK',
        'biometria':     'BIO-DATUAK',
        'mapa_politico': 'MAPA POLITIKOA',
        'cerrar':        'ITXI',
        'huir':          'IHES EGIN',
        'vats_titulo':   'V.A.T.S. — APUNTATU',
        'parte_cabeza':     'BURUA',
        'parte_torso':      'ENBORRA',
        'parte_brazo_izq':  'EZKER BESOA',
        'parte_brazo_der':  'ESKUIN BESOA',
        'parte_pierna_izq': 'EZKER HANKA',
        'parte_pierna_der': 'ESKUIN HANKA',
        'slot_cabeza':   'BURUA',
        'slot_torso':    'ENBORRA',
        'slot_mano_der': 'ARMA',
        'slot_espalda':  'MOTXILA',
        'slot_pies':     'OINAK',
        'crafteo':       'TAILERRA',
        'craftear':      'SORTU',
        'materiales':    'MATERIALAK',
        'zona_segura':       'ZONA SEGURUA',
        'zona_peligrosa':    'ZONA ARRISKUTSUA',
        'edificios':         'ERAIKINAK',
        'muerte_anterior':   'AURREKO HERIOTZA',
        'herida_abierta': 'ODOLJARIOA',
        'irradiado':      'ERRADIAZIOA',
        'infectado':      'KUTSATUTA',
        'cat_combate':       'BORROKA',
        'cat_supervivencia': 'IRAUPENA',
        'cat_recursos':      'BALIABIDEAK',
        'cat_exploracion':   'ESPLORAZIOA',
        # GERTAERAK / EVENTOS
        'ev_superviviente':  'BIZIRIK DAGOEN BAT',
        'ev_trampa':         'TRANPA DETEKTATU',
        'ev_cadaver':        'HILDAKOA BIDEAN',
        'ev_radio':          'IRRATI SEINALEA',
        'ev_lluvia':         'EURI AZIDOA',
        'ev_explosion':      'URRUNEKO LEHERKETA',
        'ev_manada':         'ZOMBIE SALDOA',
        'rescatar':          'ERRESKUTATU',
        'huir_evento':       'IHES EGIN',
        'registrar_cadaver': 'XEHATU',
        'ignorar_trampa':    'INGURATU',
        'idioma':            'HIZKUNTZA',
        'clases': {
            'Policia': 'Polizia', 'Medico': 'Medikua', 'Militar': 'Militarra',
            'Vagabundo': 'Arlotea', 'Lenador': 'Aizkolaria', 'Civil': 'Zibila',
            'Artista Marcial': 'Martial Artista', 'Catedratico': 'Katedraduna',
            'Agricultor': 'Baserritarra',
            'Policía': 'Polizia', 'Médico': 'Medikua',
            'Leñador': 'Aizkolaria', 'Catedrático': 'Katedraduna',
        },
        'objetos': {
            # armak
            'Pistola 9mm': '9mm Pistola', 'Rifle': 'Ehiza Rifle-a',
            'Escopeta': 'Escopeta', 'Hacha': 'Aizkora',
            'Cuchillo': 'Labana', 'Katana': 'Katana Herdoildua',
            'Machete': 'Matxetea', 'Bate de beisbol': 'Baseball Batea',
            'Lanza artesanal': 'Esku-egindako Lanza',
            # ekipoa
            'Exoesqueleto': 'Exoeskeleto Prototipoa',
            'Chaleco': 'Bala-kontrako Txalekoa',
            'Armadura Placas': 'Plaken Armadura',
            'Casco Militar': 'Kaska Militarra',
            'Gafas Tacticas': 'Betaurreko Taktikoak',
            'Botas Tacticas': 'Bota Taktikoak',
            'Rodilleras': 'Belaun-babesak',
            'Mochila Grande': 'Motxila Handia',
            'Mochila Tactica': 'Motxila Taktikoa',
            # sendagaiak
            'Botiquin': 'Botika-kutxa', 'Botiquín': 'Botika-kutxa',
            'Venda': 'Benda Zikina', 'Vendas': 'Bendak',
            'Lata de comida': 'Janari Lata',
            'Racion Energetica': 'Energia Anoa',
            'Agua Purificada': 'Ur Purifikatua',
            'Antibioticos': 'Antibiotikoak', 'Morfina': 'Morfina',
            'Azada': 'Golde-burua', 'Mapa': 'Mapa',
            # materialak
            'Trapo': 'Trapu Zaharra', 'Gasolina': 'Gasolina',
            'Botella vacia': 'Botila Hutsa', 'Alcohol': 'Alkohola',
            'Palo': 'Makila', 'Cuerda': 'Soka',
            'Chatarra metalica': 'Metalezko Hondakina',
            'Cable': 'Kablea', 'Lata vacia': 'Lata Hutsa',
            'Azucar': 'Azukrea', 'Agua sucia': 'Ur Zikina',
            'Pastilla potabilizadora': 'Uraren Arazgailua',
            # eginak
            'Coctel Molotov': 'Molotov Koktela',
            'Trampa Explosiva': 'Lehergailu Tranpa',
            'Botiquin Mejorado': 'Botika-kutxa Hobetua',
            'Rifle Modificado': 'Rifle Aldatua',
        },
    },
}