# -*- coding: utf-8 -*-
# traducciones.py — CRT SYSTEM v2026
# ES = Español  |  EN = English  |  EU = Euskera (Basque)

TEXTOS = {

# ══════════════════════════════════════════════════════════════
# ESPAÑOL
# ══════════════════════════════════════════════════════════════
'es': {
    # UI General
    'titulo':        'SISTEMA CRT DE SUPERVIVENCIA',
    'inicio':        'IDENTIFICACION DEL SUJETO',
    'nombre':        'NOMBRE',
    'genero':        'GENERO',
    'edad':          'EDAD',
    'lore':          'HISTORIA (opcional)',
    'origen':        'PROFESION / ORIGEN',
    'boton_inicio':  'INICIAR PROTOCOLO',
    'idioma':        'IDIOMA',
    # Stats
    'hp':            'VITALIDAD',
    'lvl':           'NIVEL',
    'exp':           'EXPERIENCIA',
    'hambre':        'NUTRICION',
    'dinero':        'CREDITOS',
    'dias':          'DIAS SOBREVIVIDOS',
    'posicion':      'SECTOR ACTUAL',
    'sp':            'PUNTOS DE MEJORA',
    'peligro':       'PELIGRO',
    # Inventario / equipo
    'mochila':       'MOCHILA',
    'materiales':    'MATERIALES',
    'curar':         'USAR',
    'atacar':        'ATACAR',
    'equipar':       'EQUIPAR',
    'desequipar':    'DESEQUIPAR',
    'durabilidad':   'DURABILIDAD',
    'municion':      'MUNICION',
    'recargar':      'RECARGAR',
    # Acciones
    'ranking':       'RANKING',
    'habilidades':   'HABILIDADES',
    'aprender':      'ADQUIRIR',
    'comprar':       'COMPRAR',
    'ignorar':       'IGNORAR',
    'cerrar':        'CERRAR',
    'huir':          'HUIR',
    'dormir':        'DORMIR',
    'crafteo':       'CRAFTEO',
    'craftear':      'CRAFTEAR',
    'explorar':      'EXPLORAR INTERIOR',
    'planos':        'PLANOS',
    'npc_hablar':    'HABLAR',
    'suicidio':      'TERMINAR PARTIDA',
    'viaje_rapido':  'VIAJE RAPIDO',
    'campamento':    'CAMPAMENTO',
    # HUD / mapa
    'estable':       'BIO-DATA ESTABLE',
    'biometria':     'BIO-DATA',
    'mapa_politico': 'MAPA POLITICO',
    'zona_segura':   'ZONA SEGURA',
    'muerte_anterior': 'MUERTE ANT.',
    # Estados negativos
    'herida_abierta':'HEMORRAGIA',
    'irradiado':     'IRRADIADO',
    'infectado':     'INFECTADO',
    'irradiado':     'IRRADIACION',
    # VATS / combate
    'vats_titulo':      'V.A.T.S. — SISTEMA DE PUNTERIA',
    'parte_cabeza':     'CABEZA',
    'parte_torso':      'TORSO',
    'parte_brazo_izq':  'BRAZO IZQ.',
    'parte_brazo_der':  'BRAZO DER.',
    'parte_pierna_izq': 'PIERNA IZQ.',
    'parte_pierna_der': 'PIERNA DER.',
    # Slots equipo
    'slot_cabeza':   'CABEZA',
    'slot_torso':    'TORSO',
    'slot_mano_der': 'ARMA',
    'slot_espalda':  'MOCHILA',
    'slot_pies':     'PIES',
    # Habilidades categorias
    'cat_combate':        'COMBATE',
    'cat_supervivencia':  'SUPERVIVENCIA',
    'cat_recursos':       'RECURSOS',
    'cat_exploracion':    'EXPLORACION',
    # Eventos
    'ev_superviviente': 'SUPERVIVIENTE',
    'ev_trampa':        'TRAMPA',
    'ev_cadaver':       'CADAVER',
    'ev_radio':         'SENAL DE RADIO',
    'rescatar':         'RESCATAR',
    'registrar_cadaver':'REGISTRAR',
    # Escape
    'escape_coche':      'ESCAPE EN COCHE',
    'escape_barco':      'ESCAPE EN BARCO',
    'escape_helicoptero':'HELICOPTERO',
    'generadores':       'GENERADORES',
    'radio_tower':       'TORRE DE RADIO',
    # Leaderboard
    'tiempo_jugado': 'TIEMPO JUGADO',
    'forma_escape':  'FORMA DE ESCAPE',
    # Mercaderes
    'mercader_armas':     'ARMERO',
    'mercader_materiales':'BUHONERO',
    'mercader_comida':    'TIENDA',
    'mercader_bazar':     'BAZAR',
    # Misc
    'biblioteca':    'BIBLIOTECA',
    'bandido':       'BANDIDO',
    'jefe':          'JEFE ZOMBI',
    'contacto':      'CONTACTO Y SUGERENCIAS',
    'genero_m':      'Masculino',
    'genero_f':      'Femenino',
    'genero_nb':     'No binario',
    # Mensajes del sistema (app.py)
    '__startup__':   'Sistemas listos. Protocolo C.R.T. activo.',
    'confirm_salir': '¿Salir de la partida?',
    'confirm_suicidio': '¿Seguro que quieres terminar?',
    'noche_text':    'NOCHE',
    'dia_text':      'DIA',
    # Bonos de clase
    'bono_policia':  'Acceso a furgones policiales.',
    'bono_medico':   '+30% efectividad curativos.',
    'bono_militar':  'Empieza con municion extra.',
    'bono_lenador':  'Armas cuerpo a cuerpo duran +50%.',
    'bono_vagabundo':'Encuentra objetos ocultos.',
    'bono_marcial':  'Punos infligen 15 de dano.',
    'bono_catedrat': '+15% XP en todas las acciones.',
    'bono_agricult': 'Cosechas rinden el doble.',
    # Items de clase (para mostrar traducido)
    'item_pistola':  'Pistola 9mm',
    'item_botiquin': 'Botiquin',
    'item_cuchillo': 'Cuchillo',
    'item_hacha':    'Hacha',
    'item_comida':   'Lata de Comida',
    'item_vendas':   'Vendas',
    'item_mapa':     'Mapa',
    'item_azada':    'Azada',
    'estado':          'ESTADO',
    'enfermedades':    'ENFERMEDADES',
    'salir':           'SALIR',
    # Footer
    'footer_proyecto':  'Proyecto de supervivencia post-apocaliptico en navegador.',
    'footer_contacto':  'Sugerencias, bugs o colaboraciones:',
    'footer_cc':        'Uso no comercial con atribucion.',
    'footer_doc_titulo':'Documentacion',
    'footer_stack':     'Python 3 · Flask · Jinja2 · SQLite3',
    'footer_frontend':  'JS Canvas · CSS CRT · VT323',
    'footer_idiomas':   'Castellano / English / Euskera',
    'footer_escapes':   'Helicoptero, Barco, Coche',
    'footer_iniciar':   'Arrancar: python app.py → :5000',
    'footer_audio':     'Audio: /static/audio/ ambient · battle',
    # Mensajes de log del juego
    '__inv_lleno__':            'Inventario lleno.',
    '__mochila_llena__':        'Mochila llena.',
    '__nada_util__':            'Nada util.',
    '__esquivaste__':           'Esquivaste!',
    '__receta_desconocida__':   'Receta desconocida.',
    '__edificio_ignorado__':    'Edificio ignorado.',
    '__coche_ignorado__':       'Coche ignorado.',
    '__rodeas_cadaver__':       'Rodeas el cadaver.',
    '__rodeas_trampa__':        'Rodeas la trampa.',
    '__sigues_adelante__':      'Sigues adelante.',
    '__te_alejas__':            'Te alejas.',
    '__sales_edificio__':       'Sales del edificio.',
    '__no_dormir_amenazas__':   'No puedes dormir con amenazas activas.',
    '__no_dormir_dia__':        'Solo puedes dormir de noche o en zona segura.',
    '__arma_no_recarga__':      'Esta arma no necesita recarga.',
    '__arma_no_municion__':     'Esta arma no usa municion.',
    '__sin_tipo_municion__':    'Sin tipo de municion definido.',
    '__campamento_construido__':'Campamento construido. Puedes dormir y cocinar aqui.',
    '__necesitas_campista__':   'Necesitas la habilidad Campista.',
    '__necesitas_campamento__': 'Necesitas un campamento primero.',
    '__ya_tienes_granja__':     'Ya tienes granja en el campamento.',
    '__necesitas_botanico__':   'Necesitas la habilidad Botanico.',
    '__sin_granja__':           'Sin granja.',
    '__ganzua_rota__':          'Ganzua rota.',
    '__cred_insuf__':           'Creditos insuficientes.',
    '__necesitas_cuerda__':     'Necesitas Cuerda para escalar la torre.',
    '__gen_ya_activo__':        'Este generador ya esta activo.',
    '__alerta_jefe__':          'ALERTA: Señal biologica CRITICA en el area.',
    # Pantallas muerte/victoria/leaderboard
    'signal_lost':          'SENAL PERDIDA',
    'unidad_terminada':     '[ UNIDAD DE SUPERVIVENCIA TERMINADA ]',
    'protocolo_abortado':   '— PROTOCOLO C.R.T. ABORTADO —',
    'reiniciar':            'REINICIAR',
    'nueva_partida':        'NUEVA PARTIDA',
    'escape_exitoso':       'ESCAPE EXITOSO',
    'protocolo_escape':     'PROTOCOLO DE ESCAPE EJECUTADO',
    'tiempo_total':         'TIEMPO TOTAL',
    'escape_helicoptero_txt':'El helicoptero aterriza en la zona segura. Evacuas la zona contaminada.',
    'escape_barco_txt':     'El barco zarpa del Puerto Fluvial. El horizonte se despeja del humo verde.',
    'escape_coche_txt':     'El motor ruge. Dejas el Sector C-7 atras a toda velocidad.',
    'escape_generico_txt':  'Lograste salir con vida.',
    'archivos_titulo':      'ARCHIVOS DE SUPERVIVENCIA',
    'archivos_sub':         'Registros del Sector C-7. Ordenados por dias sobrevividos.',
    'sin_registros':        '[!] Sin registros en el nucleo de datos.',
    'volver':               'VOLVER',
    'nombre_col':           'NOMBRE',
    'dias_col':             'DIAS',
    'tiempo_col':           'TIEMPO',
    'escape_col':           'ESCAPE',
    # Habilidades
    'hab_adquirida':        '[ ADQUIRIDA ]',
    'hab_req_prev':         '[ REQUIERE PREREQUISITO ]',
    'hab_necesitas_sp':     'NECESITAS',
    # Juego misc
    'mochila_llena':        'Mochila llena.',
    'inv_lleno':            'Inventario lleno.',
    'cred_insuf':           'Creditos insuficientes.',
    # NPC
    'sp_recompensa':        'El NPC te ha recompensado con +1 SP.',
    # Clases
    # Modales y botones faltantes
    'rodear':           'RODEAR',
    'pisar':            'PISAR',
    'entrar':           'ENTRAR',
    'cerradura':        'CERRADURA',
    'salir_edificio':   'SALIR DEL EDIFICIO',
    'comer_riesgo':     'COMER (RIESGO)',
    'slots':            'HUECOS',
    'edificio':         'EDIFICIO',
    # Eventos dinamicos (app.py genera el texto)
    'trampa_msj':       'Trampa de cables.',
    'lluvia_msj':       'Lluvia acida.',
    'manada_msj':       'Manada de {n} zombis.',
    'explosion_msj':    'Explosion lejana. El suelo tiembla.',
    'superviviente_acorralado': '{nombre} esta acorralado.',
    'superviviente_observa':    '{nombre} te observa.',
    'cadaver_msj':      'Un cadaver reciente bloquea el camino.',
    'planta_msj':       'Planta medicinal: {item}.',
    'mercader_msj':     'Mercader {nombre} aparece al amanecer.',
    'mochila_vacia':    'MOCHILA VACIA',
    'evento_activo':    'EVENTO ACTIVO',
    'progreso_escape':  'PROGRESO DE ESCAPE',
    'activa':           'ACTIVA',
    'habs': {
        'fuerza':        {'nombre':'Musculo',      'desc':'+5 de dano base.'},
        'fuerza2':       {'nombre':'Bruto',         'desc':'+8 de dano adicional.'},
        'esquivar':      {'nombre':'Evasor',        'desc':'15% de probabilidad de esquivar.'},
        'golpe_critico': {'nombre':'Ojo Clinico',   'desc':'20% de probabilidad de dano doble.'},
        'sigilo':        {'nombre':'Sombra',        'desc':'Los zombis no te detectan a distancia.'},
        'supervivencia': {'nombre':'Metabolismo',   'desc':'El hambre baja mas despacio.'},
        'supervivencia2':{'nombre':'Ayuno Extremo', 'desc':'El hambre baja mucho mas despacio.'},
        'resistencia':   {'nombre':'Piel Dura',     'desc':'+20 HP maximo.'},
        'medicina':      {'nombre':'Paramedico',    'desc':'Los curativos curan un 30% mas.'},
        'inmunidad':     {'nombre':'Inmune',        'desc':'La infeccion avanza un 50% mas lento.'},
        'carronero':     {'nombre':'Carronero',     'desc':'Mas creditos al eliminar enemigos.'},
        'mochila_ext':   {'nombre':'Mochilero',     'desc':'+2 huecos de inventario.'},
        'mochila_ext2':  {'nombre':'Cargador',      'desc':'+3 huecos adicionales.'},
        'mochila_ext3':  {'nombre':'Camionero',     'desc':'+5 huecos adicionales.'},
        'ganzua':        {'nombre':'Cerrajero',     'desc':'+1 intento al forzar cerraduras.'},
        'recolector':    {'nombre':'Recolector',    'desc':'Mas loot al saquear edificios.'},
        'agricultura':   {'nombre':'Botanico',      'desc':'Encuentra plantas medicinales.'},
        'navegacion':    {'nombre':'Orientacion',   'desc':'Mayor radio de deteccion en el radar.'},
        'velocidad':     {'nombre':'Corredor',      'desc':'La huida siempre tiene exito.'},
        'carisma':       {'nombre':'Carisma',       'desc':'Los supervivientes dan un objeto extra.'},
        'campista':      {'nombre':'Campista',      'desc':'Puedes construir un campamento base.'},
    },
    'clases': {
        'Policia':'Policia', 'Policía':'Policia',
        'Medico':'Medico',   'Médico':'Medico',
        'Militar':'Militar',
        'Lenador':'Lenador', 'Leñador':'Lenador',
        'Vagabundo':'Vagabundo',
        'Artista Marcial':'Artista Marcial',
        'Catedratico':'Catedratico','Catedrático':'Catedratico',
        'Agricultor':'Agricultor',
    },
    # Distritos
    'distritos': {
        'Parque Central':      'Parque Central',
        'Centro Urbano':       'Centro Urbano',
        'Distrito Financiero': 'Distrito Financiero',
        'Zona Militar':        'Zona Militar',
        'Puerto Fluvial':      'Puerto Fluvial',
        'Hospital':            'Hospital',
        'Zona Industrial':     'Zona Industrial',
        'Cementerio':          'Cementerio',
        'Barrio Residencial':  'Barrio Residencial',
        'Periferia':           'Periferia',
    },
    # Objetos
    'objetos': {
        'Pistola 9mm':'Pistola 9mm','Rifle':'Rifle de Caza','Escopeta':'Escopeta',
        'Ballesta':'Ballesta','Hacha':'Hacha','Cuchillo':'Cuchillo',
        'Cuchillo de cocina':'Cuchillo de Cocina','Katana':'Katana',
        'Machete':'Machete','Bate de beisbol':'Bate de Beisbol',
        'Lanza artesanal':'Lanza Artesanal','Tuberia':'Tuberia',
        'Azada':'Azada','Achuela':'Achuela','Rifle Modificado':'Rifle Modificado',
        'Ebony & Ivory':'Ebony & Ivory','Espada Crisol':'Espada Crisol',
        'Espada de Blade':'Espada de Blade','Espada del Brujo':'Espada del Brujo',
        'Excalibur':'Excalibur','Winchester 1866':'Winchester 1866',
        'Katana de Musashi':'Katana de Musashi',
        'Exoesqueleto':'Exoesqueleto','Chaleco Antibalas':'Chaleco Antibalas',
        'Chaleco':'Chaleco','Armadura Placas':'Armadura de Placas',
        'Armadura de Estatua':'Armadura de Estatua',
        'Armadura de Mansion':'Armadura de Mansion',
        'Chaqueta de Motorista':'Chaqueta de Motorista',
        'Armadura Improvisada':'Armadura Improvisada',
        'Casco Militar':'Casco Militar','Casco Improvisado':'Casco Improvisado',
        'Gafas Tacticas':'Gafas Tacticas','Botas Tacticas':'Botas Tacticas',
        'Rodilleras':'Rodilleras','Mochila Grande':'Mochila Grande',
        'Mochila Tactica':'Mochila Tactica',
        'Botiquin':'Botiquin','Venda':'Venda','Vendas':'Vendas',
        'Lata de comida':'Lata de Comida','Racion Energetica':'Racion Energetica',
        'Agua Purificada':'Agua Purificada','Antibioticos':'Antibioticos',
        'Morfina':'Morfina','Carbon Activado':'Carbon Activado',
        'Vial de Retencion':'Vial de Retencion',
        'Comida Cocinada':'Comida Cocinada','Sopa de Campamento':'Sopa de Campamento',
        'Carne de Cadaver':'Carne de Cadaver',
        'Trapo':'Trapo','Gasolina':'Gasolina','Botella vacia':'Botella Vacia',
        'Alcohol':'Alcohol','Palo':'Palo','Cuerda':'Cuerda',
        'Chatarra metalica':'Chatarra Metalica','Cable':'Cable',
        'Lata vacia':'Lata Vacia','Azucar':'Azucar','Agua sucia':'Agua Sucia',
        'Pastilla potabilizadora':'Pastilla Potabilizadora',
        'Polvora':'Polvora','Cinta americana':'Cinta Americana','Pila':'Pila',
        'Balas 9mm':'Balas 9mm','Balas Rifle':'Balas para Rifle',
        'Cartuchos':'Cartuchos','Flechas':'Flechas',
        'Pieza de Motor':'Pieza de Motor','Combustible Marino':'Combustible Marino',
        'Radio':'Radio Artesanal','Mapa':'Mapa',
        'Plano: Ballesta':'Plano: Ballesta',
        'Plano: Machete':'Plano: Machete',
        'Plano: Rifle Modificado':'Plano: Rifle Modificado',
        'Plano: Botiquin Mejorado':'Plano: Botiquin Mejorado',
        'Plano: Comida Cocinada':'Plano: Comida Cocinada',
        'Azada':'Azada','Vendas':'Vendas','Mapa':'Mapa',
    },
},

# ══════════════════════════════════════════════════════════════
# ENGLISH
# ══════════════════════════════════════════════════════════════
'en': {
    'titulo':        'CRT SURVIVAL SYSTEM',
    'inicio':        'SUBJECT IDENTIFICATION',
    'nombre':        'NAME',
    'genero':        'GENDER',
    'edad':          'AGE',
    'lore':          'BACKSTORY (optional)',
    'origen':        'PROFESSION / ORIGIN',
    'boton_inicio':  'START PROTOCOL',
    'idioma':        'LANGUAGE',
    'hp':            'VITALITY',
    'lvl':           'LEVEL',
    'exp':           'EXPERIENCE',
    'hambre':        'NUTRITION',
    'dinero':        'CREDITS',
    'dias':          'DAYS SURVIVED',
    'posicion':      'CURRENT SECTOR',
    'sp':            'SKILL POINTS',
    'peligro':       'DANGER',
    'mochila':       'BACKPACK',
    'materiales':    'MATERIALS',
    'curar':         'USE',
    'atacar':        'ATTACK',
    'equipar':       'EQUIP',
    'desequipar':    'UNEQUIP',
    'durabilidad':   'DURABILITY',
    'municion':      'AMMO',
    'recargar':      'RELOAD',
    'ranking':       'RANKING',
    'habilidades':   'SKILLS',
    'aprender':      'LEARN',
    'comprar':       'BUY',
    'ignorar':       'IGNORE',
    'cerrar':        'CLOSE',
    'huir':          'FLEE',
    'dormir':        'SLEEP',
    'crafteo':       'CRAFTING',
    'craftear':      'CRAFT',
    'explorar':      'EXPLORE INTERIOR',
    'planos':        'BLUEPRINTS',
    'npc_hablar':    'TALK',
    'suicidio':      'END GAME',
    'viaje_rapido':  'FAST TRAVEL',
    'campamento':    'CAMP',
    'estable':       'BIO-DATA STABLE',
    'biometria':     'BIO-DATA',
    'mapa_politico': 'POLITICAL MAP',
    'zona_segura':   'SAFE ZONE',
    'muerte_anterior':'PREV. DEATH',
    'herida_abierta':'BLEEDING',
    'irradiado':     'IRRADIATED',
    'infectado':     'INFECTED',
    'vats_titulo':      'V.A.T.S. — TARGETING SYSTEM',
    'parte_cabeza':     'HEAD',
    'parte_torso':      'TORSO',
    'parte_brazo_izq':  'LEFT ARM',
    'parte_brazo_der':  'RIGHT ARM',
    'parte_pierna_izq': 'LEFT LEG',
    'parte_pierna_der': 'RIGHT LEG',
    'slot_cabeza':   'HEAD',
    'slot_torso':    'TORSO',
    'slot_mano_der': 'WEAPON',
    'slot_espalda':  'BACKPACK',
    'slot_pies':     'FEET',
    'cat_combate':        'COMBAT',
    'cat_supervivencia':  'SURVIVAL',
    'cat_recursos':       'RESOURCES',
    'cat_exploracion':    'EXPLORATION',
    'ev_superviviente': 'SURVIVOR',
    'ev_trampa':        'TRAP',
    'ev_cadaver':       'CORPSE',
    'ev_radio':         'RADIO SIGNAL',
    'rescatar':         'RESCUE',
    'registrar_cadaver':'LOOT BODY',
    'escape_coche':      'CAR ESCAPE',
    'escape_barco':      'BOAT ESCAPE',
    'escape_helicoptero':'HELICOPTER',
    'generadores':       'GENERATORS',
    'radio_tower':       'RADIO TOWER',
    'tiempo_jugado': 'TIME PLAYED',
    'forma_escape':  'ESCAPE METHOD',
    'mercader_armas':     'ARMS DEALER',
    'mercader_materiales':'SCAVENGER',
    'mercader_comida':    'FOOD SHOP',
    'mercader_bazar':     'BAZAAR',
    'biblioteca':    'LIBRARY',
    'bandido':       'BANDIT',
    'jefe':          'BOSS ZOMBIE',
    'contacto':      'CONTACT & SUGGESTIONS',
    'genero_m':      'Male',
    'genero_f':      'Female',
    'genero_nb':     'Non-binary',
    '__startup__':   'Systems ready. C.R.T. Protocol active.',
    'confirm_salir': 'Quit game?',
    'confirm_suicidio': 'Are you sure you want to end?',
    'noche_text':    'NIGHT',
    'dia_text':      'DAY',
    'bono_policia':  'Access to police vans.',
    'bono_medico':   '+30% healing effectiveness.',
    'bono_militar':  'Starts with extra ammo.',
    'bono_lenador':  'Melee weapons last +50%.',
    'bono_vagabundo':'Finds hidden items.',
    'bono_marcial':  'Fists deal 15 damage.',
    'bono_catedrat': '+15% XP in all actions.',
    'bono_agricult': 'Harvests yield double.',
    # Clases
        # Modal buttons
    'rodear':           'GO AROUND',
    'pisar':            'STEP ON',
    'entrar':           'ENTER',
    'cerradura':        'LOCK',
    'salir_edificio':   'LEAVE BUILDING',
    'comer_riesgo':     'EAT (RISK)',
    'slots':            'SLOTS',
    'edificio':         'BUILDING',
    'trampa_msj':       'Cable trap.',
    'lluvia_msj':       'Acid rain.',
    'manada_msj':       'Pack of {n} zombies.',
    'explosion_msj':    'Distant explosion. The ground shakes.',
    'superviviente_acorralado': '{nombre} is cornered.',
    'superviviente_observa':    '{nombre} watches you.',
    'cadaver_msj':      'A fresh corpse blocks the path.',
    'planta_msj':       'Medicinal plant: {item}.',
    'mercader_msj':     'Merchant {nombre} appears at dawn.',
    'mochila_vacia':    'BACKPACK EMPTY',
    'evento_activo':    'ACTIVE EVENT',
    'progreso_escape':  'ESCAPE PROGRESS',
    'activa':           'ACTIVE',
    'habs': {
        'fuerza':        {'nombre':'Muscle',        'desc':'+5 base damage.'},
        'fuerza2':       {'nombre':'Brute',          'desc':'+8 additional damage.'},
        'esquivar':      {'nombre':'Dodger',         'desc':'15% chance to dodge attacks.'},
        'golpe_critico': {'nombre':'Clinical Eye',   'desc':'20% chance for double damage.'},
        'sigilo':        {'nombre':'Shadow',         'desc':'Zombies do not detect you at range.'},
        'supervivencia': {'nombre':'Metabolism',     'desc':'Hunger decreases more slowly.'},
        'supervivencia2':{'nombre':'Extreme Fasting','desc':'Hunger decreases much more slowly.'},
        'resistencia':   {'nombre':'Tough Skin',     'desc':'+20 maximum HP.'},
        'medicina':      {'nombre':'Paramedic',      'desc':'Healing items cure 30% more.'},
        'inmunidad':     {'nombre':'Immune',         'desc':'Infection spreads 50% slower.'},
        'carronero':     {'nombre':'Scavenger',      'desc':'More credits when killing enemies.'},
        'mochila_ext':   {'nombre':'Backpacker',     'desc':'+2 inventory slots.'},
        'mochila_ext2':  {'nombre':'Carrier',        'desc':'+3 additional slots.'},
        'mochila_ext3':  {'nombre':'Hauler',         'desc':'+5 additional slots.'},
        'ganzua':        {'nombre':'Locksmith',      'desc':'+1 attempt when picking locks.'},
        'recolector':    {'nombre':'Looter',         'desc':'More loot when searching buildings.'},
        'agricultura':   {'nombre':'Botanist',       'desc':'Finds medicinal plants.'},
        'navegacion':    {'nombre':'Navigation',     'desc':'Greater detection range on radar.'},
        'velocidad':     {'nombre':'Runner',         'desc':'Fleeing always succeeds.'},
        'carisma':       {'nombre':'Charisma',       'desc':'Survivors give an extra item.'},
        'campista':      {'nombre':'Camper',         'desc':'You can build a base camp.'},
    },
    'clases': {
        'Policia':'Police Officer','Policía':'Police Officer',
        'Medico':'Doctor','Médico':'Doctor',
        'Militar':'Soldier',
        'Lenador':'Lumberjack','Leñador':'Lumberjack',
        'Vagabundo':'Drifter',
        'Artista Marcial':'Martial Artist',
        'Catedratico':'Professor','Catedrático':'Professor',
        'Agricultor':'Farmer',
    },
    'distritos': {
        'Parque Central':'Central Park','Centro Urbano':'Urban Center',
        'Distrito Financiero':'Financial District','Zona Militar':'Military Zone',
        'Puerto Fluvial':'River Port','Hospital':'Hospital',
        'Zona Industrial':'Industrial Zone','Cementerio':'Cemetery',
        'Barrio Residencial':'Residential Area','Periferia':'Outskirts',
    },
    'objetos': {
        'Pistola 9mm':'9mm Pistol','Rifle':'Hunting Rifle','Escopeta':'Shotgun',
        'Ballesta':'Crossbow','Hacha':'Hand Axe','Cuchillo':'Knife',
        'Cuchillo de cocina':'Kitchen Knife','Katana':'Katana',
        'Machete':'Machete','Bate de beisbol':'Baseball Bat',
        'Lanza artesanal':'Improvised Spear','Tuberia':'Iron Pipe',
        'Azada':'Hoe','Achuela':'Hatchet','Rifle Modificado':'Modified Rifle',
        'Ebony & Ivory':'Ebony & Ivory','Espada Crisol':'Crucible Blade',
        'Espada de Blade':"Blade's Sword",'Espada del Brujo':'Warlock Blade',
        'Excalibur':'Excalibur','Winchester 1866':'Winchester 1866',
        'Katana de Musashi':"Musashi's Katana",
        'Exoesqueleto':'Exoskeleton','Chaleco Antibalas':'Bulletproof Vest',
        'Chaleco':'Vest','Armadura Placas':'Plate Armor',
        'Armadura de Estatua':'Statue Armor','Armadura de Mansion':'Manor Armor',
        'Chaqueta de Motorista':'Biker Jacket','Armadura Improvisada':'Improvised Armor',
        'Casco Militar':'Military Helmet','Casco Improvisado':'Improvised Helmet',
        'Gafas Tacticas':'Tactical Goggles','Botas Tacticas':'Tactical Boots',
        'Rodilleras':'Knee Pads','Mochila Grande':'Large Backpack',
        'Mochila Tactica':'Tactical Backpack',
        'Botiquin':'Med Kit','Venda':'Bandage','Vendas':'Bandages',
        'Lata de comida':'Canned Food','Racion Energetica':'Energy Ration',
        'Agua Purificada':'Purified Water','Antibioticos':'Antibiotics',
        'Morfina':'Morphine','Carbon Activado':'Activated Charcoal',
        'Vial de Retencion':'Retention Vial',
        'Comida Cocinada':'Cooked Food','Sopa de Campamento':'Camp Stew',
        'Carne de Cadaver':'Corpse Meat',
        'Trapo':'Rag','Gasolina':'Gasoline','Botella vacia':'Empty Bottle',
        'Alcohol':'Alcohol','Palo':'Stick','Cuerda':'Rope',
        'Chatarra metalica':'Metal Scrap','Cable':'Wire',
        'Lata vacia':'Empty Can','Azucar':'Sugar','Agua sucia':'Dirty Water',
        'Pastilla potabilizadora':'Purif. Tablet',
        'Polvora':'Gunpowder','Cinta americana':'Duct Tape','Pila':'Battery',
        'Balas 9mm':'9mm Rounds','Balas Rifle':'Rifle Rounds',
        'Cartuchos':'Shells','Flechas':'Arrows',
        'Pieza de Motor':'Engine Part','Combustible Marino':'Marine Fuel',
        'Radio':'Handmade Radio','Mapa':'Map',
        'Plano: Ballesta':'Blueprint: Crossbow',
        'Plano: Machete':'Blueprint: Machete',
        'Plano: Rifle Modificado':'Blueprint: Modified Rifle',
        'Plano: Botiquin Mejorado':'Blueprint: Advanced Med Kit',
        'Plano: Comida Cocinada':'Blueprint: Cooked Food',
    },
},

# ══════════════════════════════════════════════════════════════
# EUSKERA (Basque)
# ══════════════════════════════════════════════════════════════
'eu': {
    'titulo':        'CRT IRAUPENA SISTEMA',
    'inicio':        'SUBJEKTUAREN IDENTIFIKAZIOA',
    'nombre':        'IZENA',
    'genero':        'GENEROA',
    'edad':          'ADINA',
    'lore':          'HISTORIA (aukerakoa)',
    'origen':        'LANBIDEA / JATORRIA',
    'boton_inicio':  'PROTOKOLOA HASI',
    'idioma':        'HIZKUNTZA',
    'hp':            'BIZITZA-ENERGIA',
    'lvl':           'MAILA',
    'exp':           'ESPERIENTZIA',
    'hambre':        'ELIKADURA',
    'dinero':        'KREDITUAK',
    'dias':          'BIZIRAUTEKO EGUNAK',
    'posicion':      'UNEKO SEKTOREA',
    'sp':            'TREBETASUN PUNTUAK',
    'peligro':       'ARRISKUA',
    'mochila':       'ZAKUA',
    'materiales':    'MATERIALAK',
    'curar':         'ERABILI',
    'atacar':        'ERASO',
    'equipar':       'EKIPATU',
    'desequipar':    'DESEKIPATU',
    'ekipamendua':   'EKIPAMENDUA',   # ← tab de equipo en euskera
    'durabilidad':   'IRAUNKORTASUNA',
    'municion':      'MUNIZIO',
    'recargar':      'KARGATU',
    'ranking':       'RANKINGA',
    'habilidades':   'TREBETASUNAK',
    'aprender':      'IKASI',
    'comprar':       'EROSI',
    'ignorar':       'EZIKUSI',
    'cerrar':        'ITXI',
    'huir':          'IHES EGIN',
    'dormir':        'LO EGIN',
    'crafteo':       'TAILERRA',
    'craftear':      'SORTU',
    'explorar':      'BARNEA ARAKATU',
    'planos':        'PLANOAK',
    'npc_hablar':    'HITZ EGIN',
    'suicidio':      'PARTIDA BUKATU',
    'viaje_rapido':  'BIDAIA AZKARRA',
    'campamento':    'KANPALEKUA',
    'estable':       'BIO-DATUAK EGONKORRAK',
    'biometria':     'BIO-DATUAK',
    'mapa_politico': 'MAPA POLITIKOA',
    'zona_segura':   'EREMU SEGURUA',
    'muerte_anterior':'AURREKO HERIOTZA',
    'herida_abierta':'ODOLJARIOA',
    'irradiado':     'ERRADIAZIOA',
    'infectado':     'KUTSATUTA',
    'vats_titulo':      'V.A.T.S. — JOMUGEN SISTEMA',
    'parte_cabeza':     'BURUA',
    'parte_torso':      'ENBORRA',
    'parte_brazo_izq':  'EZKER BESOA',
    'parte_brazo_der':  'ESKUIN BESOA',
    'parte_pierna_izq': 'EZKER HANKA',
    'parte_pierna_der': 'ESKUIN HANKA',
    'slot_cabeza':   'BURUA',
    'slot_torso':    'ENBORRA',
    'slot_mano_der': 'ARMA',
    'slot_espalda':  'ZAKUA',
    'slot_pies':     'OINAK',
    'cat_combate':        'BORROKA',
    'cat_supervivencia':  'IRAUPENA',
    'cat_recursos':       'BALIABIDEAK',
    'cat_exploracion':    'ESPLORAZIOA',
    'ev_superviviente': 'BIZIRIK DAGOENA',
    'ev_trampa':        'TRANPA',
    'ev_cadaver':       'HILDAKOA',
    'ev_radio':         'IRRATI SEINALEA',
    'rescatar':         'ERRESKUTATU',
    'registrar_cadaver':'GORPUA ARAKATU',
    'escape_coche':      'AUTOAN IHES',
    'escape_barco':      'ONTZIAN IHES',
    'escape_helicoptero':'HELIKOPTEROA',
    'generadores':       'SORTZAILEAK',
    'radio_tower':       'IRRATI DORREA',
    'tiempo_jugado': 'JOKATUTAKO DENBORA',
    'forma_escape':  'IHES MODUA',
    'mercader_armas':     'ARMA SALTZAILEA',
    'mercader_materiales':'BILTZAILEA',
    'mercader_comida':    'JANARI DENDA',
    'mercader_bazar':     'BAZAR',
    'biblioteca':    'LIBURUTEGIA',
    'bandido':       'BANDIDOA',
    'jefe':          'JEFE ZOMBIA',
    'contacto':      'KONTAKTUA ETA IRADOKIZUNAK',
    'genero_m':      'Gizonezkoa',
    'genero_f':      'Emakumezkoa',
    'genero_nb':     'Ez-binarioa',
    '__startup__':   'Sistemak prest. C.R.T. Protokoloa aktibo.',
    'confirm_salir': 'Partida utzi?',
    'confirm_suicidio': 'Ziur amaitu nahi duzula?',
    'noche_text':    'GAUA',
    'dia_text':      'EGUNA',
    'bono_policia':  'Polizia furgonetetarako sarbidea.',
    'bono_medico':   '+30% sendagaien eraginkortasuna.',
    'bono_militar':  'Munizio gehiagorekin hasten da.',
    'bono_lenador':  'Arma zuriak %50 gehiago irauten du.',
    'bono_vagabundo':'Ezkutuko objektuak aurkitzen ditu.',
    'bono_marcial':  'Ukabilek 15 kalte egiten dute.',
    'bono_catedrat': '+15% XP ekintza guztietan.',
    'bono_agricult': 'Uztak bikoitza ematen du.',
    # Clases
        # Modal botoiak
    'rodear':           'INGURATU',
    'pisar':            'ZAPATU',
    'entrar':           'SARTU',
    'cerradura':        'SARRAIL',
    'salir_edificio':   'ERAIKINETIK IRTEN',
    'comer_riesgo':     'JAN (ARRISKUA)',
    'slots':            'LEKUAK',
    'edificio':         'ERAIKINA',
    'trampa_msj':       'Kableen tranpa.',
    'lluvia_msj':       'Azido euria.',
    'manada_msj':       '{n} zombien taldea.',
    'explosion_msj':    'Urruneko leherketa. Lurra dar-dar.',
    'superviviente_acorralado': '{nombre} inguratuta dago.',
    'superviviente_observa':    '{nombre}k begiratzen zaitu.',
    'cadaver_msj':      'Hildako freski batek bidea blokeatzen du.',
    'planta_msj':       'Landare sendagarria: {item}.',
    'mercader_msj':     '{nombre} saltzailea egunsentia baino lehen agertzen da.',
    'mochila_vacia':    'ZAKUA HUTSIK',
    'evento_activo':    'EKINTZA AKTIBO',
    'progreso_escape':  'IHES AURRERAPEN',
    'activa':           'AKTIBO',
    'habs': {
        'fuerza':        {'nombre':'Muskulu',        'desc':'+5 oinarrizko kalte.'},
        'fuerza2':       {'nombre':'Bortitza',       'desc':'+8 kalte gehigarri.'},
        'esquivar':      {'nombre':'Iheslaria',      'desc':'%15 eraso saihesteko probabilitatea.'},
        'golpe_critico': {'nombre':'Begi Klinikoa',  'desc':'%20 kalte bikoitza egiteko probabilitatea.'},
        'sigilo':        {'nombre':'Itzala',         'desc':'Zombiek ez zaituzte urrunetik detektatzen.'},
        'supervivencia': {'nombre':'Metabolismoa',   'desc':'Gosearen beherakada mantsoagoa.'},
        'supervivencia2':{'nombre':'Baraua',         'desc':'Gosearen beherakada askoz mantsoagoa.'},
        'resistencia':   {'nombre':'Larru Gogorra',  'desc':'+20 HP maximoa.'},
        'medicina':      {'nombre':'Paramedikoa',    'desc':'Sendagaiek %30 gehiago sendatzen dute.'},
        'inmunidad':     {'nombre':'Immunea',        'desc':'Infekzioa %50 mantsoago hedatzen da.'},
        'carronero':     {'nombre':'Belatza',        'desc':'Kreditu gehiago etsaiak hiltzerakoan.'},
        'mochila_ext':   {'nombre':'Zakularia',      'desc':'+2 inbentario hutsune.'},
        'mochila_ext2':  {'nombre':'Kargatzen',      'desc':'+3 hutsune gehigarri.'},
        'mochila_ext3':  {'nombre':'Kamioia',        'desc':'+5 hutsune gehigarri.'},
        'ganzua':        {'nombre':'Zerrajaria',     'desc':'+1 saiakera sarraila forzatzerakoan.'},
        'recolector':    {'nombre':'Biltzailea',     'desc':'Loot gehiago eraikinetan arakatzerakoan.'},
        'agricultura':   {'nombre':'Botanikoa',      'desc':'Landare sendagarriak aurkitzen ditu.'},
        'navegacion':    {'nombre':'Orientazioa',    'desc':'Detekzio erradio handiagoa.'},
        'velocidad':     {'nombre':'Korrikaria',     'desc':'Ihesa beti arrakastatsua da.'},
        'carisma':       {'nombre':'Karisma',        'desc':'Bizirauteko aurkitutakoek objektu bat gehiago ematen dute.'},
        'campista':      {'nombre':'Kanpalaria',     'desc':'Oinarrizko kanpaleku bat eraiki dezakezu.'},
    },
    'clases': {
        'Policia':'Polizia','Policía':'Polizia',
        'Medico':'Medikua','Médico':'Medikua',
        'Militar':'Militarra',
        'Lenador':'Aizkolaria','Leñador':'Aizkolaria',
        'Vagabundo':'Arlotea',
        'Artista Marcial':'Martial Artista',
        'Catedratico':'Katedraduna','Catedrático':'Katedraduna',
        'Agricultor':'Baserritarra',
    },
    'distritos': {
        'Parque Central':      'Erdiguneko Parkea',
        'Centro Urbano':       'Hiri Gunea',
        'Distrito Financiero': 'Finantza Barrutia',
        'Zona Militar':        'Eremu Militarra',
        'Puerto Fluvial':      'Ibai Portua',
        'Hospital':            'Ospitalea',
        'Zona Industrial':     'Industria Gunea',
        'Cementerio':          'Hilerria',
        'Barrio Residencial':  'Etxe Barrutia',
        'Periferia':           'Periferia',
    },
    'objetos': {
        'Pistola 9mm':'9mm Pistola','Rifle':'Ehiza Rifle','Escopeta':'Escopeta',
        'Ballesta':'Balezta','Hacha':'Aizkora','Cuchillo':'Labana',
        'Cuchillo de cocina':'Sukaldeko Labana','Katana':'Katana',
        'Machete':'Matxetea','Bate de beisbol':'Baseball Batea',
        'Lanza artesanal':'Esku-egindako Lanza','Tuberia':'Burdin Hodia',
        'Azada':'Goldea','Achuela':'Aizkora Txikia',
        'Rifle Modificado':'Aldatutako Rifle',
        'Ebony & Ivory':'Ebony & Ivory','Espada Crisol':'Galdaketa Ezpata',
        'Espada de Blade':'Blade-ren Ezpata',
        'Espada del Brujo':'Sorginaren Ezpata',
        'Excalibur':'Excalibur','Winchester 1866':'Winchester 1866',
        'Katana de Musashi':'Musashiren Katana',
        'Exoesqueleto':'Exoeskeletoa',
        'Chaleco Antibalas':'Bala-kontrako Txalekoa',
        'Chaleco':'Txalekoa',
        'Armadura Placas':'Plaken Armadura',
        'Armadura de Estatua':'Eskulturaren Armadura',
        'Armadura de Mansion':'Jauregiaren Armadura',
        'Chaqueta de Motorista':'Motorreko Jaka',
        'Armadura Improvisada':'Armadura Inprobisatua',
        'Casco Militar':'Kaska Militarra',
        'Casco Improvisado':'Kaska Inprobisatua',
        'Gafas Tacticas':'Betaurreko Taktikoak',
        'Botas Tacticas':'Bota Taktikoak',
        'Rodilleras':'Belaun-babesak',
        'Mochila Grande':'Zaku Handia',
        'Mochila Tactica':'Zaku Taktikoa',
        'Botiquin':'Botika-kutxa','Venda':'Benda','Vendas':'Bendak',
        'Lata de comida':'Janari Lata',
        'Racion Energetica':'Energia Anoa',
        'Agua Purificada':'Ur Purifikatua',
        'Antibioticos':'Antibiotikoak',
        'Morfina':'Morfina',
        'Carbon Activado':'Ikatz Aktibatua',
        'Vial de Retencion':'Erretentzio Biala',
        'Comida Cocinada':'Prestatutako Janaria',
        'Sopa de Campamento':'Kanpalekuko Zopa',
        'Carne de Cadaver':'Hildakoaren Haragia',
        'Trapo':'Trapu Zaharra','Gasolina':'Gasolina',
        'Botella vacia':'Botila Hutsa','Alcohol':'Alkohola',
        'Palo':'Makila','Cuerda':'Soka',
        'Chatarra metalica':'Metalezko Hondakina',
        'Cable':'Kablea','Lata vacia':'Lata Hutsa',
        'Azucar':'Azukrea','Agua sucia':'Ur Zikina',
        'Pastilla potabilizadora':'Uraren Arazgailua',
        'Polvora':'Bolboraa','Cinta americana':'Amerikan Zinta',
        'Pila':'Bateria',
        'Balas 9mm':'9mm Balak','Balas Rifle':'Rifle Balak',
        'Cartuchos':'Kartutxoak','Flechas':'Geziak',
        'Pieza de Motor':'Motor Pieza',
        'Combustible Marino':'Itsas Erregaia',
        'Radio':'Esku-egindako Irratia',
        'Mapa':'Mapa',
        'Plano: Ballesta':'Planoa: Balezta',
        'Plano: Machete':'Planoa: Matxetea',
        'Plano: Rifle Modificado':'Planoa: Aldatutako Rifle',
        'Plano: Botiquin Mejorado':'Planoa: Botika-kutxa Hobetua',
        'Plano: Comida Cocinada':'Planoa: Prestatutako Janaria',
    },
},

}